# Data Setting
batch_size: 128
data_dir: data/mixamo
num_joints: 22
workers: 8

# Network Setting
network: simple_bn

# Training Setting
vis_overfit: false
overfit: false
nepoch: 1000
reproduce: true
## Learning Rate Setting
lr: 1e-3
lr_gamma: 1.0
lr_step_size: 5
## Logging Setting
time: true
save_epoch: 1
vis_epoch: 10



